/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsNameRouteImport } from './routes/teams.$name'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsNameRoute = TeamsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => TeamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/news': typeof NewsRoute
  '/players': typeof PlayersRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/teams/$name': typeof TeamsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/news': typeof NewsRoute
  '/players': typeof PlayersRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/teams/$name': typeof TeamsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/news': typeof NewsRoute
  '/players': typeof PlayersRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/teams/$name': typeof TeamsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/matches'
    | '/news'
    | '/players'
    | '/standings'
    | '/teams'
    | '/teams/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matches'
    | '/news'
    | '/players'
    | '/standings'
    | '/teams'
    | '/teams/$name'
  id:
    | '__root__'
    | '/'
    | '/matches'
    | '/news'
    | '/players'
    | '/standings'
    | '/teams'
    | '/teams/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesRoute: typeof MatchesRoute
  NewsRoute: typeof NewsRoute
  PlayersRoute: typeof PlayersRoute
  StandingsRoute: typeof StandingsRoute
  TeamsRoute: typeof TeamsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$name': {
      id: '/teams/$name'
      path: '/$name'
      fullPath: '/teams/$name'
      preLoaderRoute: typeof TeamsNameRouteImport
      parentRoute: typeof TeamsRoute
    }
  }
}

interface TeamsRouteChildren {
  TeamsNameRoute: typeof TeamsNameRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsNameRoute: TeamsNameRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesRoute: MatchesRoute,
  NewsRoute: NewsRoute,
  PlayersRoute: PlayersRoute,
  StandingsRoute: StandingsRoute,
  TeamsRoute: TeamsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
